# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: boss track slice demise into boy blanket rigid hill trust run awake

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
